"""redid instance

Revision ID: c9afeeb5512f
Revises: 
Create Date: 2024-08-30 15:00:49.092530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9afeeb5512f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('jobsite_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('startdate', sa.String(), nullable=False),
    sa.Column('enddate', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_jobsite_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['jobsite_table.id'], name=op.f('fk_images_table_jobsite_id_jobsite_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datelist', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['jobsite_table.id'], name=op.f('fk_material_table_jobsite_id_jobsite_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prints_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['jobsite_table.id'], name=op.f('fk_prints_table_jobsite_id_jobsite_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punchlist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('jobsite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobsite_id'], ['jobsite_table.id'], name=op.f('fk_punchlist_table_jobsite_id_jobsite_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punchlist_table')
    op.drop_table('prints_table')
    op.drop_table('material_table')
    op.drop_table('images_table')
    op.drop_table('jobsite_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
